update data generation script for NeRF over fitting. Modified dataset to data loading
zubair-irshad/articulated-object-nerf pull request #6
Opened 2023-08-27 11:51 UTC by DJNing

1. data generation in /dataset/data_gen.py
2. sapien dataset now loads the path for the specific object. ( e.g., /path_to_object/{train, val, test})
3. dataset now load focal length directly

2023-08-27 18:18 UTC, zubair-irshad commented
Thanks a lot for your contribution, I left some minor comments!

2023-08-28 09:42 UTC, DJNing commented
hi, I am not sure where to check your comments.

2023-08-28 11:34 UTC, zubair-irshad commented
@DJNing if you scroll up in this PR i.e. conversation tab, you will see my comments with each code block. Please let me know if you are still not able to find them, thanks again for your contributions

2023-08-28 13:34 UTC, DJNing commented
<img width="776" alt="截屏2023-08-28 14 32 53" src="https://github.com/zubair-irshad/articulated-object-nerf/assets/29802444/18bfca9e-dd07-4cec-af6c-30114a804188">
Do you mean this one? The top left one guides me back here. Thanks again for your patience.

2023-08-28 13:38 UTC, zubair-irshad commented
No I meant these ones:

<img width="769" alt="image" src="https://github.com/zubair-irshad/articulated-object-nerf/assets/32943733/70287831-10b6-4b45-88fd-eb40f18e4ecb">


<img width="761" alt="image" src="https://github.com/zubair-irshad/articulated-object-nerf/assets/32943733/2ea4cdbd-ddf8-4a66-bcc4-5a3ae7daa325">

<img width="629" alt="image" src="https://github.com/zubair-irshad/articulated-object-nerf/assets/32943733/d2bba792-faa6-48f9-a542-c23e2583c021">

2023-08-28 13:39 UTC, zubair-irshad commented
Sorry for the confusion, usually github notifies one directly on the email where one can access these review comments

2023-08-28 13:42 UTC, DJNing commented
<img width="1211" alt="截屏2023-08-28 14 41 31" src="https://github.com/zubair-irshad/articulated-object-nerf/assets/29802444/f688da0f-5975-412c-9987-9c46b27abc13">
It seems they are not visible on my side, perhaps?

2023-08-28 13:53 UTC, zubair-irshad requested changes

2023-08-28 13:53 UTC, zubair-irshad commented on datasets/sapien.py
> +            self.base_dir_val = os.path.join(base_dir, 'test')
Would this change require modification to the current small dataset provided in the repo? i.e. the directory structure in which the current data is saved

2023-08-28 13:53 UTC, zubair-irshad commented on datasets/data_gen.py
Any qualitative examples you could share of the generated data or the poses to make sure they look correct? Perhaps we could consider adding those to readme as well under a small heading i.e. generate your own data?

2023-08-28 13:53 UTC, zubair-irshad commented on datasets/sapien.py
> +            self.base_dir_val = os.path.join(base_dir, 'test')
Also, should we add the new example training script to our readme based on this change? i.e. the scripts mentioned under this [heading](https://github.com/zubair-irshad/articulated-object-nerf#-training-and-inference)

2023-08-28 13:53 UTC, zubair-irshad commented on datasets/data_utils.py
> +        point = random_point_in_sphere(radius=radius_, theta_range=theta_range, phi_range=phi_range)
should we move this globally? In my current data gen script locally, I first generate camera poses globally and feed that as input to the rendering function (similar to this) to render images. This helps with consistency across all instances :) For a single instance i.e. overfitting, it doesn't matter but would be useful if one wants to generate data for multiple instances so camera poses for all of them remain the same

2023-08-28 13:54 UTC, zubair-irshad commented
Could you please check now?

2023-08-28 13:54 UTC, DJNing commented
yes, I could see them now, thank you

2023-08-28 13:58 UTC, DJNing commented on datasets/sapien.py
> +            self.base_dir_val = os.path.join(base_dir, 'test')
For Q1, it's compatible with the provided dataset in the repo. It basically means
```base_dir = os.path.join(base_dir, instance_dir, instance_id, degree_id)```
So, just pass the parent dir of {train, val, test} would be fine.

For Q2, yes, changing the readme would be good for other users.

2023-08-28 14:01 UTC, zubair-irshad commented on datasets/sapien.py
> +            self.base_dir_val = os.path.join(base_dir, 'test')
For Q2, could you please add the new script to Readme since it is a direct result of this change? Thank you

2023-08-28 14:02 UTC, DJNing commented on datasets/data_utils.py
> +        point = random_point_in_sphere(radius=radius_, theta_range=theta_range, phi_range=phi_range)
Hi, for the pose generation, the camera pose is actually generated in the render_pose function. Here I just pick a point in the sphere and suggest the camera is facing towards the origin (0, 0, 0).

I will think of some modifications to this. Reloading the camera pose from the transform.json could be an easier way to keep pose consistency. What do you think?

2023-08-28 14:07 UTC, DJNing commented on datasets/data_gen.py
I've got validation results after the training.
![Untitled](https://github.com/zubair-irshad/articulated-object-nerf/assets/29802444/506e9a6a-87c3-47d9-9132-5d6349c21785)

2023-08-28 14:10 UTC, zubair-irshad commented on datasets/data_utils.py
> +        point = random_point_in_sphere(radius=radius_, theta_range=theta_range, phi_range=phi_range)
I totally agree, in fact, this is how I currently do it i.e. save poses in a JSON file globally and load it for all instances so hemispherical poses remain the same across instances. IMO this is better for generalizable training and evaluation and I think NASAM also does it like this

2023-08-28 14:11 UTC, zubair-irshad commented on datasets/data_gen.py
Thank you, do you mind including them in the readme as additional qualitative results?

BTW I meant if you have multi-view and multi-articulation snapshot of the generated data, it would be good to include that in the reamde as well?

2023-08-28 14:12 UTC, zubair-irshad commented on datasets/data_gen.py
Something like this (or with the camera poses)

<img width="162" alt="image" src="https://github.com/zubair-irshad/articulated-object-nerf/assets/32943733/0fc4a4df-8c05-45f2-9b14-ac80f12f3cba">

2023-08-28 14:22 UTC, DJNing commented
Hi, I am also new to the PR. Could you also check the codes for later commits? Or only the first commit?

2023-08-28 14:25 UTC, zubair-irshad commented
Thanks let me review other commits as well.

2023-08-28 15:03 UTC, DJNing commented on datasets/data_gen.py
I will do that later

2023-08-29 21:46 UTC, zubair-irshad reviewed
Can you please add all of these changes to the readme? i.e. how to run scripts with config files?

2023-08-29 21:48 UTC, zubair-irshad commented on datasets/data_gen.py
okay thanks, not so urgent but would be good to add to the readme when you can for visibility purposes i.e. also for the users to know what to expect from the datagen scripts

2023-08-29 21:49 UTC, zubair-irshad commented on datasets/data_gen.py
We need to add the datagen scripts to the readme i.e. how to generate their own data

2023-08-29 21:49 UTC, zubair-irshad commented on datasets/data_utils.py
> +        point = random_point_in_sphere(radius=radius_, theta_range=theta_range, phi_range=phi_range)
Have you included this change already in newer commits?

2023-08-30 10:05 UTC, DJNing commented
readme is modified in the latest commit
now we can render images with saved pose
data generation for different articulations is not supported yet.

2023-08-30 16:25 UTC, zubair-irshad requested changes

2023-08-30 16:25 UTC, zubair-irshad commented on README.md
> +    ![Image](./pics/data_folder_tree.png)
Maybe replace it with this which is more readable?

```
scissor
├── test
├── train
│   ├── depth
│   ├── rgb
│   └── transforms.json
└── val
```

2023-08-30 16:35 UTC, zubair-irshad commented on README.md
> +    ![Image](./pics/data_folder_tree.png)
resolving in a follow-up commit, thanks for all the changes

2023-08-30 16:35 UTC, merged